services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_READ_TOPIC: ingest-tasks
      KAFKA_PROCESS_DATA_TASKS_TOPIC: process-tasks
      KAFKA_BOOTSTRAP_SERVERS: kafka-compose-kafka-broker-1:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ingests
    networks:
      - global

networks:
  global:
    external: true